version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy                              # mysql container 실행 대기

  db:
    platform: linux/amd64
    image: mysql:5.7.34
    restart: always
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    healthcheck:                                                  # mysql container 실행이 끝나고 backend container 실행
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
